Add OSX CLI instructions
singron/old-reddit-fmt-bot pull request #2
Opened 2019-08-28 06:34 UTC by masklinn

I'd have provided a pre-built workflow but they're annoying to distribute and inspect, so giving the instructions for people to create their own workflow is slightly less convenient for them but much more trustworthy.

Though I guess they could be provided as a "release" on this project or something? Just commit the entire bundle directory then zip it up for distribution? IDK.

2019-08-28 15:58 UTC, singron requested changes
Thanks for you contribution! I think I agree about distributing opaque files myself, especially since I don't use OSX and wouldn't be able to personally vouch for their integrity.

I spotted one small typo when I previewed and I'm happy to merge once it's fixed.

2019-08-28 15:58 UTC, singron commented on about.md
> +* replace the text (`cat`) by `sed 's/^/    /'
Looks like you are missing a trailing `` ` ``?

2019-08-29 05:57 UTC, masklinn commented on about.md
> +* replace the text (`cat`) by `sed 's/^/    /'
Should be fixed, thanks.

2019-08-29 05:58 UTC, masklinn commented
> I think I agree about distributing opaque files myself

Yeah, they're not opaque per-se (it's a bundle with two XML plist files) but it still seems like as much work as re-doing it by hand. A more complex workflow might make sense to distribute directly but that's not one.

2019-08-29 15:16 UTC, singron approved these changes
Thanks again. I wasn't expecting contributions so quickly so this was a very pleasant outcome.

2019-08-29 15:18 UTC, merged